version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/fbw.stonelabs.io/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/letsencrypt/live/fbw.stonelabs.io/privkey.pem:/etc/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443

  fbw_api:
    image: nistei/fbw-api:latest
    container_name: fbw_api
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mysql
    expose:
      - 3000

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
