version: "3.3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - DHPARAM_GENERATION=false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certificates:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certificates:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  fbw_api:
    image: nistei/fbw-api:latest
    container_name: fbw_api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - VIRTUAL_HOST=${API_URL}
      - LETSENCRYPT_HOST=${API_URL}
      - VIRTUAL_PORT=3000
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_HOST=redis
      - AUTH_SECRET_FILE=/run/secrets/jwt_secret
    depends_on:
      - redis
      - mysql
    secrets:
      - db_password
      - jwt_secret
    expose:
      - 3000

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    expose:
      - 6379

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=fbw
      - MYSQL_USER=fbw
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    expose:
      - 3306

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - VIRTUAL_HOST=${MAP_URL}
      - LETSENCRYPT_HOST=${MAP_URL}
      - VIRTUAL_PORT=3000
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=fbw
      - DATABASE_USER=fbw
    volumes:
      - ./grafana:/etc/grafana
    expose:
      - 5000

volumes:
  nginx-certificates:
  nginx-vhosts:
  nginx-html:

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  jwt_secret:
    file: secrets/jwt_secret.txt
