version: "3.3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - DHPARAM_GENERATION=false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-certificates:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certificates:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  fbw_api:
    image: flybywiresim/api:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - VIRTUAL_HOST=${API_URL}
      - LETSENCRYPT_HOST=${API_URL}
      - VIRTUAL_PORT=3000
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_HOST=redis
      - AUTH_SECRET_FILE=/run/secrets/jwt_secret
      - TELEX_TIMEOUT_MIN=${TELEX_TIMEOUT_MIN}
    depends_on:
      - redis
    secrets:
      - db_password
      - jwt_secret
    expose:
      - 3000

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    expose:
      - 6379

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${LOG_SIZE}"
        max-file: "${LOG_COUNT}"
    environment:
      - VIRTUAL_HOST=${MAP_URL}
      - LETSENCRYPT_HOST=${MAP_URL}
      - VIRTUAL_PORT=3000
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_USER=${DATABASE_GRAFANA_USER}
    volumes:
      - ./grafana:/etc/grafana
      - grafana-storage:/var/lib/grafana
    expose:
      - 5000

volumes:
  nginx-certificates:
  nginx-vhosts:
  nginx-html:
  grafana-storage:

secrets:
  db_password:
    file: secrets/db_password.txt
  jwt_secret:
    file: secrets/jwt_secret.txt
