version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api.flybywiresim.com/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/letsencrypt/live/api.flybywiresim.com/privkey.pem:/etc/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443

  fbw_api:
    image: nistei/fbw-api:latest
    container_name: fbw_api
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_HOST=redis
      - AUTH_SECRET_FILE=/run/secrets/jwt_secret
    depends_on:
      - redis
      - mysql
    secrets:
      - db_password
      - jwt_secret
    expose:
      - 3000

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=fbw
      - MYSQL_USER=fbw
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    expose:
      - 3306

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=fbw
      - DATABASE_USER=fbw
    volumes:
      - ./grafana:/etc/grafana
    expose:
      - 5000

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  jwt_secret:
    file: secrets/jwt_secret.txt
