ingress:
  fqdn: api.staging.flybywiresim.com
  tls:
    enabled: true
    issuer: letsencrypt-prod

api:
  database:
    host: private-mysql-flybywiresim-do-user-8167919-0.b.db.ondigitalocean.com
    port: 25060
    database: fbw_api_staging
    user: fbw_api_staging
    replicas:
      - private-mysql-flybywiresim-read-only-83073-do-user-8167919-0.b.db.ondigitalocean.com
  redis:
    host: redis-staging-master.redis-staging.svc.cluster.local
  telex:
    timeoutMin: 15
    disableCleanup: true
