name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build_and_push:
    name: Build a Docker image and push the image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: nistei/fbw-api
          tag_with_ref: true
