name: Master CI

on:
  push:
    branches: main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: flybywiresim/api:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy_prod:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Depoy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          passphrase: ${{ secrets.PROD_PASSPHRASE }}
          script_stop: true
          script: |
            cd api
            git fetch --all
            git reset --hard origin/main
            docker-compose --env-file ./envs/.env.prod pull
            docker-compose --env-file ./envs/.env.prod up -d --scale fbw_api=2
            docker system prune -af
